### ISSUE TITLE
ODP Connector Issue

### ISSUE THREAD

**Issue by johnnymullaney** [optimizely/marketingautomationintegration-odp#1]
Hi, After installing the nuget package and adding the app setting I get the following:

![image](https://user-images.githubusercontent.com/19771039/184921164-eb633faa-d371-4812-a64c-aeb73db51173.png)

CMS 11
Optimizely.Labs.MarketingAutomationIntegration.ODP 0.0.8

Is this a known issue?

Thanks

**Comment by daniel-isaacs** [comment]
I have several CMS 11 sites up and running with the package installed, and haven't seen an issue like that. Is there anything helpful in the logs?

**Comment by daniel-isaacs** [comment]
One issue I have seen with the CMS 11 version is if you have a form mapped to ODP, and you have the EPiServer.Marketing.Automation.Forms package installed, you should disable Auto-fill (CMS > Admin > Config tab > Marketing Connectors Global Settings > uncheck "Enable Auto-fill on forms:" > click Save).

But I think that's unrelated (it only throws an error when the form is rendered on the page).

**Comment by johnnymullaney** [comment]
Hi Daniel,

The issue was the endpoint was hardcoded to api.zaius.com and not configurable for EU. 

I see you have fixed that in your latest pull request:

https://github.com/optimizely/marketingautomationintegration-odp/pull/2

Issue resolved.

Thank you
